### ISSUE TITLE
Message Forbidden error

### ISSUE THREAD

**Issue by sigmatwo** [dvsa/mot-public-api#47]
When using any of the curl examples with my own API key shown at: https://www.check-mot.service.gov.uk/mot-history-api I cannot return anything other than: {"message":"Forbidden"}

My API key was issued in December 2017 so presume should still be valid. Any ideas why this isn't working?

OS: High Sierra 10.13.3. iTerm 3.1.5

**Comment by jerotire** [comment]
First off, apologies for the long delay.

We have verified that the curl examples provided in the [MOT History API documentation](https://www.check-mot.service.gov.uk/mot-history-api) are correct and are working. This was most likely an authentication issue with the API key.

I'm closing this issue as it is over a year old; I will also make a note to watch for issues more regularly on our repositories.

If errors such as this occurs in the future, please use this link to report an issue:

https://www.smartsurvey.co.uk/s/MOT_History_TradeAPI_Access_and_Support/
