### ISSUE TITLE
Are there plans for additional fields to be added in the response?

### ISSUE THREAD

**Issue by oayres** [dvsa/mot-public-api#86]
Hey there,

We're looking to integrate with this API and have an API key we've tested out. It's a brilliant service and we love what you're doing!

For what we need, we'd also like the following bits of information when we do a look-up if possible:
- Date of last V5C (logbook) issued
- Tax status
- Tax expiry date
- VIN
- Revenue weight
- Vehicle type approval
- Wheelplan

I understand some of the above isn't necessarily within the scope of what the core intentions are for providing this API, but do you think any of the above info is likely to be part of the roadmap for this service?

Alternatively, in absence of this, do you know if there is any other way of retrieving said info via a gov digital API?

Cheers,
Owen

**Comment by ibrahimjassat** [comment]
Thank you for your enquiry, please can you forward this enquiry to the MOT enquires mailbox here - mot@dvsa.gov.uk
